Naive Bayes

In [272]:
import numpy as np
import pandas as pd
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.naive_bayes import MultinomialNB 
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import svc
from sklearn.model_selection import cross_val_score

ImportError: cannot import name 'svc' from 'sklearn.svm' (C:\Users\Inayat\anaconda3\lib\site-packages\sklearn\svm\__init__.py)

In [203]:
irisds=load_iris()

In [204]:
irisds

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [205]:
irisds.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [206]:
irisds.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [207]:
irisds.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [208]:
irisds.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [209]:
irisds.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [210]:
df=pd.DataFrame(irisds.data)
df

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [211]:
df=pd.DataFrame(irisds.data,columns=irisds.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [212]:
df['target']=pd.DataFrame(irisds.target)

In [213]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [214]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [215]:
df.to_csv("myiris.csv")#to save the file and to observe al values in the table

In [216]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [217]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
145       2  
146       2  
147       2  
148       2  
149       2

In [218]:
x=df.iloc[:,0:-1]

In [219]:
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [220]:
y=df.iloc[:,-1]

In [221]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [222]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=45)

In [223]:
x_train.shape

(105, 4)

In [224]:
x_test.shape

(45, 4)

In [225]:
y_train.shape


(105,)

In [226]:
y_test.shape

(45,)

In [227]:
mnb=MultinomialNB()

In [228]:
mnb.fit(x_train,y_train)

MultinomialNB()

In [229]:
predmnb=mnb.predict(x_test)

In [230]:
predmnb

array([0, 0, 1, 0, 0, 0, 0, 2, 1, 2, 0, 1, 2, 2, 1, 0, 2, 2, 0, 1, 1, 1,
       2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 2, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1])

In [231]:
accuracy_score(y_test,predmnb)

0.8666666666666667

In [232]:
print(confusion_matrix(y_test,predmnb))

[[17  0  0]
 [ 0 13  0]
 [ 0  6  9]]


In [233]:
print(classification_report(y_test,predmnb))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.68      1.00      0.81        13
           2       1.00      0.60      0.75        15

    accuracy                           0.87        45
   macro avg       0.89      0.87      0.85        45
weighted avg       0.91      0.87      0.86        45



In [234]:
p=np.array([5.1,3.5,1.4,0.2])


In [235]:
p.shape

(4,)

In [236]:
p=p.reshape(1,-1)
p.shape

(1, 4)

In [237]:
mnb.predict(p)

array([0])

In [238]:
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [239]:
preddtc=dtc.predict(x_test)
preddtc

array([0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 1, 1,
       2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 2, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1,
       1])

In [240]:
accuracy_score(y_test,preddtc)

0.9555555555555556

In [241]:
print(confusion_matrix(y_test,preddtc))

[[17  0  0]
 [ 0 13  0]
 [ 0  2 13]]


In [242]:
print(classification_report(y_test,preddtc))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.87      1.00      0.93        13
           2       1.00      0.87      0.93        15

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.95        45
weighted avg       0.96      0.96      0.96        45



In [243]:
dtc.predict(p)

array([0])

In [244]:
k=np.array([5.9,3.0,5.1,1.8])

In [245]:
k

array([5.9, 3. , 5.1, 1.8])

In [246]:
k.shape


(4,)

In [247]:
k=k.reshape(1,-1)


In [248]:
k.shape

(1, 4)

In [249]:
dtc.predict(k)

array([2])

In [250]:


def testpredict(j):
    j=j.reshape(1,-1)
    pr=dtc.predict(j)
    print(pr)
    if pr==0:
        print('setosa')
    elif pr==1:
        print('versicular')
    elif pr==2: 
        print('verginica')
j=np.array([5.9,3.0,5.1,1.8])
testpredict(j)

[2]
verginica


In [251]:
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
predknn=knn.predict(x_test)
predknn

array([0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 1, 1,
       2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 2, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1,
       1])

METRICS

In [252]:
accuracy_score(y_test,predknn)

0.9555555555555556

In [253]:
print(confusion_matrix(y_test,predknn))

[[17  0  0]
 [ 0 13  0]
 [ 0  2 13]]


In [254]:
print(classification_report(y_test,predknn))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.87      1.00      0.93        13
           2       1.00      0.87      0.93        15

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.95        45
weighted avg       0.96      0.96      0.96        45



In [255]:
j=np.array([4.6,3.1,1.5,0.2])
testpredict(j)
def testpredict(j):
    j=j.reshape(1,-1)
    pr=knn.predict(j)
    print(pr)
    if pr==0:
        print('setosa')
    elif pr==1:
        print('versicular')
    elif pr==2: 
        print('verginica')

[0]
setosa


In [256]:
sv=SVC(kernel='rbf')

In [257]:
sv.fit(x_train,y_train)

SVC()

In [258]:
predsv=sv.predict(x_test)
predsv

array([0, 0, 2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 1, 1,
       2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 2, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1,
       1])

In [259]:
accuracy_score(y_test,predsv)

0.9333333333333333

In [260]:
confusion_matrix(y_test,predsv)

array([[17,  0,  0],
       [ 0, 13,  0],
       [ 0,  3, 12]], dtype=int64)

In [274]:
sv=SVC(kernel='poly')
sv.fit(x_train,y_train)
predsv=sv.predict(x_test)
predsv

array([0, 0, 1, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 1, 1,
       2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 2, 2, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1,
       1])

In [262]:
accuracy_score(y_test,predsv)

0.9555555555555556

In [263]:
sv=SVC(kernel='linear')
sv.fit(x_train,y_train)
predsv=sv.predict(x_test)
predsv

array([0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 1, 1, 1,
       2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 2, 2, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1,
       1])

In [264]:
accuracy_score(y_test,predsv)

1.0

In [265]:
confusion_matrix(y_test,predsv)

array([[17,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 15]], dtype=int64)

In [266]:
print(classification_report(y_test,predsv))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        15

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [267]:
j=np.array([4.6,3.1,1.5,0.2])
testpredict(j)
def testpredict(j):
    j=j.reshape(1,-1)
    pr=sv.predict(j)
    print(pr)
    if pr==0:
        print('setosa')
    elif pr==1:
        print('versicular')
    elif pr==2: 
        print('verginica')

[0]
setosa


In [277]:
from sklearn.svm import SVR
kernellist=['linear','poly','rbf']
for i in kernellist:
    sv=SVR((kernel==i)
    sv.fit(x_train,y_train)
    print(sv.score(x_train,y_train))

SyntaxError: invalid syntax (Temp/ipykernel_8864/2459270350.py, line 5)

In [ ]:
score=cross_val_score(mnb,x,y,cv=5)

print(score)
print(score.mean())
print(score.std())

In [ ]:
from sklearn.svm import SVC

In [270]:
score=cross_val_score(sv,x,y,cv=5)

print(score)
print(score.mean())
print(score.std())

[0.96666667 1.         0.96666667 0.96666667 1.        ]
0.9800000000000001
0.016329931618554516


saving the best model


In [276]:
import joblib
joblib.dump(sv,'svfile.obj')
dtc_from_joblib=joblib.load('svfile.obj')
dtc_from_joblib.predict(x_test)

array([0, 0, 1, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 1, 1,
       2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 2, 2, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1,
       1])

In [279]:
import pickle
filename='pickledtcfile.pkl'
pickle.dump(dtc,open(filename,'wb'))
loaded_model=pickle.load(open(filename,'rb'))
loaded_model.predict(x_test)

array([0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 1, 1,
       2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 2, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1,
       1])